[Interface]
PrivateKey = qETo+SIE5Gttl8nSRCI3jiD18ZJjrwqkwcgh8n/XyUw=
Address = 10.8.1.0/24
ListenPort = 443
Jc = 3
Jmin = 10
Jmax = 50
S1 = 106
S2 = 17
H1 = 891876870
H2 = 1202676760
H3 = 479848242
H4 = 1400026040

[Peer]
PublicKey = WhYkLXCMrCV1sja2qmcvueDRgfqS0l37J+je+eY2ikg=
PresharedKey = 4ytGE7CEbk7hNForwWWem4cRcRilxDBSJrELUE7Hi5s=
AllowedIPs = 10.8.1.2/32
